name: publish-site-gh-pages
on:
  push:
    branches:
      - master
jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: compile
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: compile

      - name: test
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: test

      - name: generate html site
        uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: enableSocco; compile;

      - name: publish to github pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
