name: publish-site-gh-pages
on:
  push:
    branches:
      - master
jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: compile
  test:
    name: test
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: test
  publish-gh-pages:
    name: Publish to github pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@v0.2.2
        with:
          commands: clean enableSocco compile
